config/routes.rb
Rails.application.routes.draw do
  resources :programmes
  resources :degrees
  resources :applications, only: [:create, :show, :destroy]

  resources :job_offers, path: '/emprego' do
    collection do
      get 'estudantes/:random_id' => 'job_offers#students', as: :students
    end
  end

  devise_for :users
  resources :users do
    collection do
      resources :profiles
    end
  end

  match 'perfil' => 'profiles#show', as: :my_profile, via: :get
  match 'perfil/editar' => 'profiles#edit', as: :edit_my_profile, via: :get
  match 'utilizador' => 'users#show', as: :my, via: :get

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  root 'pages#index'
end

app/models/profile.rb
class Profile < ApplicationRecord

  belongs_to :user
  belongs_to :programme
  validates_presence_of :name, :user

  after_create :make_student

  has_attached_file :curriculum, {
    storage: :ftp,
    path: ENV['ftp_path'] + "/curriculum/:id/:filename",
    url: ENV['http_path'] + "/curriculum/:id/:filename",
    ftp_servers: [
      {
        host: ENV['ftp_host'],
        user: ENV['ftp_user'],
        password: ENV['ftp_password'],
        passive: true
      }
    ]
  }

  validates_attachment_content_type :curriculum, content_type: "application/pdf"

  def make_student
    self.user.make_student
  end

  def email
    self.user.email
  end

  def degree
    self.programme.degree.name
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  load_and_authorize_resource except: [:show, :edit]
  before_action :set_user
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  layout 'devise'

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    authorize! :manage, @profile
    if can? :manage, Profile
      render :admin_show
    end
  end

  # GET /profiles/new
  def new
    unless @user.profile.blank?
      redirect_to edit_user_profile_path(id: @user.profile, user_id: @user)
    end
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
    authorize! :manage, @profile
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    if @user == current_user
      @profile.user = @user
    end

    respond_to do |format|
      if @profile.save
        if @profile.user == current_user
          format.html { redirect_to my_path, notice: 'Profile was successfully created.' }
        else
          format.html { redirect_to @user, notice: 'Profile was successfully created.' }
        end
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    if profile_params[:curriculum] == ''
      @profile.curriculum = nil
    end
    respond_to do |format|
      if @profile.update(profile_params)
        if @profile.user == current_user
          format.html { redirect_to my_path, notice: 'Profile was successfully updated.' }
        else
          format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        end
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = @user.profile
      @profile ||= Profile.find params[:id]
      @user = @profile.user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :curriculum, :phone, :programme_id)
    end

    def set_user
      @user = current_user
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(profile) do |f| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :phone, 'Telefone' %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :programme_id, 'Curso' %>
    <%= f.collection_select :programme_id, Programme.left_outer_joins(:degree).order("degrees.order", :name), :id, :full_name %>
  </div>

  <div class="actions">
    <%= f.button 'Gravar', class: 'button expanded' %>
  </div>
<% end %>

app/views/profiles/admin_show.html.erb
<% title @profile.name %>

<p>
  <strong>Email:</strong>
  <%= @profile.email %>
</p>

<%= link_to fa_icon('pencil lg', text: 'Edit'), edit_profile_path(@profile), class: 'button' %>
<%= link_to fa_icon('user lg', text: @profile.name), user_path(@user), class: 'button' %>

app/views/profiles/edit.html.erb
<% title 'Alterar Perfil' %>
<%= render 'form', profile: @profile %>

app/views/profiles/index.html.erb
<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>
        <td><%= profile.user %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<% title 'Criar Perfil' %>
<%= render 'form', profile: @profile %>

app/views/profiles/show.html.erb
<% title @profile.name %>

<p>
  <strong>Email:</strong>
  <%= @profile.email %>
</p>

<%= link_to fa_icon('pencil lg', text: 'Edit'), edit_my_profile_path, class: 'button' %>
<%= link_to fa_icon('user lg', text: @profile.name), my_path, class: 'button' %>