config/routes.rb
Rails.application.routes.draw do
  resources :programmes
  resources :degrees
  resources :applications, only: [:create, :show, :destroy]

  resources :job_offers, path: '/emprego' do
    collection do
      get 'estudantes/:random_id' => 'job_offers#students', as: :students
    end
  end

  devise_for :users
  resources :users do
    collection do
      resources :profiles
    end
  end

  match 'perfil' => 'profiles#show', as: :my_profile, via: :get
  match 'perfil/editar' => 'profiles#edit', as: :edit_my_profile, via: :get
  match 'utilizador' => 'users#show', as: :my, via: :get

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  root 'pages#index'
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :confirmable, :recoverable, :rememberable, :trackable, :validatable
  
  after_create :assign_default_role

  has_one :profile, dependent: :destroy
  has_many :applications, dependent: :destroy
  has_many :views, foreign_key: :user_id, class_name: "JobView", dependent: :destroy

  accepts_nested_attributes_for :applications

  def assign_default_role
    self.add_role :newuser if self.roles.blank?
  end

  def assign_role new_role
    self.remove_role :newuser
    self.add_role new_role
  end

  def make_student
    self.assign_role :student
  end

  def name
    if self.profile.blank?
      return self.email
    else
      return self.profile.name
    end
  end

  def create_view job_offer
    if self.has_role? :student
      JobView.create_later(self, job_offer)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource except: :show
  before_action :set_user, only: [:show, :update]

  def index
    role = Role.find_by(name: 'student')
    if role
      @users = role.users
    else
      @users = {}
    end
    render layout: 'admin'
  end

  def show
    authorize! :manage, @user

    if @user == current_user
      @profile = @user.profile
    end

    if can? :manage, User
      render :admin_show
    end
  end

  def update
    if @user.update(user_params)
      redirect_to job_offers_path, notice: 'User atualizado'
    else
      redirect_to job_offers_path, notice: 'Erro a atualizar utilizador'
    end
  end

  private
    def user_params
      params.require(:user).permit(application: [:user_id, :job_offer_id])
    end

    def set_user
      if params[:id].blank?
        @user = current_user
      else
        @user = User.find params[:id]
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/admin_show.html.erb
<% title @user.name %>

<div>
  <% if can? :manage, User %>
    <%= link_to 'Perfil', profile_path(@user.profile) %>
  <% else %>
    <% if @user.has_role? :student %>
      <%= link_to 'Perfil', my_profile_path %>
    <% end %>
  <% end %>
</div>

app/views/users/index.html.erb
<% title 'Utilizadores' %>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Nome</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.email, user %></td>
          <td><%= user.name %></td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<% title @user.name %>

<div class="col" id="user-profile">
  <% if can? :manage, User %>
    <%= link_to 'Perfil', profile_path(@user.profile) %>
  <% elsif can? :manage, @user %>
    <% if !@profile.blank? %>
      <h2><%= @profile.name %></h2>

      <h5>Curriculum Vitae</h5>
      <div id="curriculum-upload">
        <% if @profile.curriculum? %>
          <%= link_to fa_stacked_icon('check lg', base: 'file-pdf-o', class: 'fa-3x'), @profile.curriculum.url, target: '_blank', id: 'curriculum-url' %>
          <%= link_to fa_stacked_icon('times lg', base: 'file-pdf-o', class: 'fa-3x'), "#", target: '_blank', id: 'curriculum-missing', class: 'invalid hidden' %>
        <% else %>
          <%= link_to fa_stacked_icon('check lg', base: 'file-pdf-o', class: 'fa-3x'), @profile.curriculum.url, target: '_blank', id: 'curriculum-url', class: 'hidden' %>
          <%= link_to fa_stacked_icon('times lg', base: 'file-pdf-o', class: 'fa-3x'), "#", target: '_blank', id: 'curriculum-missing', class: 'invalid' %>
        <% end %>

        <%= form_for @profile, html: {id: 'curriculum-upload-form'} do |f| %>
          <span class='button' id="curriculum-upload-button">Upload</br>(Arrastar ficheiro para aqui)</span>
        <% end %>

        <%= form_for @profile do |f| %>
          <%= f.hidden_field :curriculum, value: nil %>
          <% if @profile.curriculum? %>
            <%= f.button fa_icon('trash 3x'), class: 'curriculum-destroy alert button' %>
          <% else %>
            <%= f.button fa_icon('trash 3x'), class: 'curriculum-destroy alert button hidden' %>
          <% end %>
        <% end %>
      </div>

      <div class="profile-details">
        <h5>Dados de <%= @profile.name %><small><%= link_to fa_icon('pencil fw'), edit_my_profile_path %></small></h5>
        <span><strong>Telefone:</strong> <%= @profile.phone %></span>
        <span><strong>Curso:</strong> [<%= @profile.degree %>] <%= @profile.programme.name %></span>
        
      </div>
    <% end %>

    <span><%= link_to fa_icon('lock', text: 'Alterar dados de acesso'), edit_registration_path(current_user) %></span>
    <span><%= link_to fa_icon('sign-out', text: 'Sair'), destroy_user_session_path, method: :delete, class: 'alert' %></span>
  <% end %>
</div>