config/routes.rb
Rails.application.routes.draw do
  resources :programmes
  resources :degrees
  resources :applications, only: [:create, :show, :destroy]

  resources :job_offers, path: '/emprego' do
    collection do
      get 'estudantes/:random_id' => 'job_offers#students', as: :students
    end
  end

  devise_for :users
  resources :users do
    collection do
      resources :profiles
    end
  end

  match 'perfil' => 'profiles#show', as: :my_profile, via: :get
  match 'perfil/editar' => 'profiles#edit', as: :edit_my_profile, via: :get
  match 'utilizador' => 'users#show', as: :my, via: :get

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  root 'pages#index'
end

app/models/degree.rb
class Degree < ApplicationRecord
  has_many :programmes, dependent: :destroy
end

app/controllers/degrees_controller.rb
class DegreesController < ApplicationController
  load_and_authorize_resource
  before_action :set_degree, only: [:show, :edit, :update, :destroy]

  layout 'admin'

  # GET /degrees
  # GET /degrees.json
  def index
    @degrees = Degree.order :order
  end

  # GET /degrees/1
  # GET /degrees/1.json
  def show
    @programmes = @degree.programmes.order :name
    @new_programme = Programme.new(degree: @degree)
  end

  # GET /degrees/new
  def new
    @degree = Degree.new
  end

  # GET /degrees/1/edit
  def edit
  end

  # POST /degrees
  # POST /degrees.json
  def create
    @degree = Degree.new(degree_params)

    respond_to do |format|
      if @degree.save
        format.html { redirect_to @degree, notice: 'Degree was successfully created.' }
        format.json { render :show, status: :created, location: @degree }
      else
        format.html { render :new }
        format.json { render json: @degree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /degrees/1
  # PATCH/PUT /degrees/1.json
  def update
    respond_to do |format|
      if @degree.update(degree_params)
        format.html { redirect_to @degree, notice: 'Degree was successfully updated.' }
        format.json { render :show, status: :ok, location: @degree }
      else
        format.html { render :edit }
        format.json { render json: @degree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /degrees/1
  # DELETE /degrees/1.json
  def destroy
    @degree.destroy
    respond_to do |format|
      format.html { redirect_to degrees_url, notice: 'Degree was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_degree
      @degree = Degree.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def degree_params
      params.require(:degree).permit(:name, :order)
    end
end

app/helpers/degrees_helper.rb
module DegreesHelper
end

app/views/degrees/_form.html.erb
<%= form_for(degree) do |f| %>
  <% if degree.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(degree.errors.count, "error") %> prohibited this degree from being saved:</h2>

      <ul>
      <% degree.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="fields-horizontal">
    <div class="field">
      <%= f.label :name, 'Nome' %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :order, 'Posição' %>
      <%= f.number_field :order, step: 1, min: 1, max: 10 %>
    </div>
  </div>

  <div class="actions">
    <%= f.button fa_icon('save lg', text: 'Gravar'), class: 'button' %>
  </div>
<% end %>

app/views/degrees/edit.html.erb
<div class="menu">
  <%= link_to fa_icon('level-up lg fw', text: 'Graus Académicos'), Degree, class: 'button' %>
</div>

<h1><%= title "Editar #{@degree.name}" %></h1>

<%= render 'form', degree: @degree %>

app/views/degrees/index.html.erb
<% title 'Cursos' %>

<table>
  <thead>
    <tr>
      <th>Grau Académico</th>
      <th>Ordem</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @degrees.each do |degree| %>
      <tr>
        <td><%= link_to degree.name, degree %></td>
        <td><%= degree.order %></td>
        <td class='text-right'>
          <%= link_to fa_icon('pencil fw'), edit_degree_path(degree) %>
          <%= link_to fa_icon('trash fw'), degree, method: :delete, class: 'alert', data: { confirm: 'Tem a certeza?' } %>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="menu">
  <%= link_to fa_icon('plus lg fw', text: 'Grau Académico'), new_degree_path, class: 'button' %>
</div>

app/views/degrees/new.html.erb
<div class="menu">
  <%= link_to fa_icon('list lg fw', text: 'Graus Académicos'), Degree, class: 'button' %>
</div>

<h1><%= title 'Criar Grau Académico' %></h1>

<%= render 'form', degree: @degree %>

app/views/degrees/show.html.erb
<div class="menu">
  <%= link_to fa_icon('level-up lg fw', text: 'Graus Académicos'), Degree, class: 'button' %>
</div>

<h1>
  <span><%= title @degree.name %></span>
</h1>

<table>
  <thead>
    <tr>
      <th>Curso</th>
      <th colspan></th>
    </tr>
  </thead>

  <tbody>
    <% @programmes.each do |programme| %>
      <tr>
        <td><%= link_to programme.name, edit_programme_path(programme) %></td>
        <td class='text-right'>
          <%= link_to fa_icon('trash fw'), programme, method: :delete, class: 'alert', data: { confirm: 'Tem a certeza?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= form_for(@new_programme) do |f| %>
  <% if @new_programme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@new_programme.errors.count, "error") %> prohibited this programme from being saved:</h2>

      <ul>
      <% @new_programme.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :degree_id %>

  <div class="fields-horizontal">
    <div class="field">
      <%= f.text_field :name, placeholder: 'Curso' %>
    </div>

    <div class="actions">
      <%= f.button fa_icon('save lg', text: 'Adicionar'), class: 'button' %>
    </div>
  </div>
<% end %>