config/routes.rb
Rails.application.routes.draw do
  resources :programmes
  resources :degrees
  resources :applications, only: [:create, :show, :destroy]

  resources :job_offers, path: '/emprego' do
    collection do
      get 'estudantes/:random_id' => 'job_offers#students', as: :students
    end
  end

  devise_for :users
  resources :users do
    collection do
      resources :profiles
    end
  end

  match 'perfil' => 'profiles#show', as: :my_profile, via: :get
  match 'perfil/editar' => 'profiles#edit', as: :edit_my_profile, via: :get
  match 'utilizador' => 'users#show', as: :my, via: :get

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  root 'pages#index'
end

app/views/layouts/_adminmenu.html.erb
<div id="adminmenu">
  <%= link_to 'Estudantes', users_path %>
  <%= link_to 'Cursos', degrees_path %>
  <%= link_to 'Ofertas de Emprego', job_offers_path %>
</div>

app/views/layouts/_head.html.erb
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />


  <%= display_meta_tags site: 'AEISCAL Emprego', reverse: true %>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

app/views/layouts/_menubar.html.erb
<header id="menubar">
  <div class="left">
    <%= link_to root_path do %>
      <%= image_tag 'logo-white.png' %>
    <% end %>
  </div>

  <div class="center">
    <strong><%= link_to 'Portal de Emprego AEISCAL', root_path %></strong>
  </div>

  <div class="right">
    <% if user_signed_in? %>
      <% if current_user.has_role? :admin %>
        <%= link_to fa_icon('sign-out', text: 'Sair'), destroy_user_session_path, method: :delete, class: 'alert' %>
      <% else %>
        <%= link_to fa_icon('user fw', text: current_user.name), my_path %>
      <% end %>
    <% else %>
      <%= link_to fa_icon('briefcase fw', text: 'Nova Oferta'), new_job_offer_path %>
      <%= link_to fa_icon('lock fw', text: 'Entrar'), new_user_session_path %>
    <% end %>
  </div>
</header>

app/views/layouts/_notice.html.erb
<% if notice or alert %>
  <div id="notice">
    <%= notice %><%= alert %>
  </div>
<% end %>

app/views/layouts/_sidebar.html.erb
<div id="sidebar">
  <div class="sidebar-container">
    <%= image_tag 'model.jpg'%>

    <ul id='sidemenu' class='vertical menu text-left'>
      <li><%= link_to 'Perfil', current_user %></li>
      <li><%= link_to 'Emprego', job_offers_path %></li>
    </ul>
  </div>

  <ul id='exit' class='vertical menu'>
    <%= link_to fa_icon('lock fw', text: 'Sair'), destroy_user_session_path, method: :delete %>
  </ul>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <%= render 'layouts/head' %>

  <body>
    <%= render 'layouts/menubar' %>
    <%= render 'layouts/adminmenu' %>

    <div class="page">
      <div class="admin-content">
        <%= yield %>
      </div>
    </div>
  </body>

  <%= render 'layouts/notice' %>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <%= render 'layouts/head' %>

  <body>
    <%= render 'layouts/menubar' %>
    <%= render 'layouts/notice' %>

    <div class="page">
      <%= yield %>
    </div>
  </body>

</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
  <%= render 'layouts/head' %>

  <body>
    <%= render 'layouts/menubar' %>
    <%= render 'layouts/notice' %>

    <div id="devise" class="page">
      <h1><%= title %></h1>
      <%= yield %>
    </div>
  </body>

</html>

app/views/layouts/job_offer.html.erb
<!DOCTYPE html>
<html lang="en">
  <%= render 'layouts/head' %>

  <body>
    <%= render 'layouts/menubar' %>
    <%= render 'layouts/notice' %>

    <div id="adminmenu">
      <ul class="menu expanded">
        <li>
          <%= link_to fa_icon('caret-square-o-down fw', text: 'Curso', right: true), '' %>
          <ul class="submenu">
            <li><%= link_to 'Todos', job_offers_path(search_params.except(:programme)) %></li>
            <% Programme.left_outer_joins(:degree).order('degrees.order', :name).each do |programme| %>
              <li><%= link_to programme.full_name, job_offers_path(search_params(programme: programme)) %></li>
            <% end %>
          </ul>
        </li>

        <li>
          <%= link_to fa_icon('caret-square-o-down fw', text: 'Localização', right: true), '' %>
          <ul class="submenu">
            <li><%= link_to 'Todos', job_offers_path(search_params.except(:location)) %></li>
            <% JobOffer.locations.each do |location| %>
              <li><%= link_to location, job_offers_path(search_params(location: location)) %></li>
            <% end %>
          </ul>
        </li>

        <li>
          <%= link_to fa_icon('caret-square-o-down fw', text: 'Contrato', right: true), '' %>
          <ul class="submenu">
            <li><%= link_to 'Todos', job_offers_path(search_params.except(:contract)) %></li>
            <% JobOffer.types_of_contract.each do |contract| %>
              <li><%= link_to contract, job_offers_path(search_params(contract: contract)) %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>

    <div class="page">
      <%= yield %>
    </div>
  </body>

</html>

app/views/layouts/no-padding.html.erb
<!DOCTYPE html>
<html lang="en">
  <%= render 'layouts/head' %>

  <body>
    <%= render 'layouts/menubar' %>
    <%= render 'layouts/notice' %>

    <div class="page no-padding">
      <%= yield %>
    </div>
  </body>

</html>